### ISSUE TITLE
Assign reviewers, assignees, and milestone to pull request

### ISSUE THREAD

**Issue by zanerock** [liquid-labs/liq-work#97]
## Overview

The 'assignee' is the submitter.

The reviewer is chosen at random from the project (repo) collaborators minus the submitter, unless that would leave the pool empty, in which case the single collaborator is assigned as a reviewer.

The milestone is set to match the current (== semver logic earliest non-closed) milestone (minus backlog).

## Deliverables

- [x] Update PR assignee.
- [x] Update PR reviewer.
- [x] Update PR milestone.
